~/miniconda3/bin/conda build vtk
~/miniconda3/bin/conda build liblas
~/miniconda3/bin/conda build flann
~/miniconda3/bin/conda build pcl
~/miniconda3/bin/conda build python-pcl
~/miniconda3/bin/conda build texture-atlas
~/miniconda3/bin/conda build core3d-purdue
~/miniconda3/bin/conda build laspy
~/miniconda3/bin/conda build pubgeo-tools
~/miniconda3/bin/conda build pubgeo-core3d-metrics
~/miniconda3/bin/conda build gaia
