package:
  name: core3d-tf_ops
  version: 0.0.6

source:
  patches:
    - core3d-tf_ops.patch
  git_branch: master
  git_url: https://github.com/charlesq34/pointnet2.git

requirements:
  build:
    - tensorflow-gpu=1.9.0
  run:
    - tensorflow-gpu=1.9.0
